# Generated by Django 2.0.2 on 2018-12-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20181227_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fill_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_or_false',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
