# Generated by Django 2.0.2 on 2018-12-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20181227_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
    ]
