# Generated by Django 2.0.2 on 2019-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_auto_20190107_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='mc', max_length=3),
            preserve_default=False,
        ),
    ]
