# Generated by Django 2.0.2 on 2019-01-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_auto_20190109_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='answer_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_results', to='quizzes.Answer'),
        ),
    ]
