# Generated by Django 2.0.2 on 2019-01-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_auto_20190109_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_results', to='quizzes.Answer'),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
