# Generated by Django 2.0.2 on 2019-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_auto_20190110_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='default_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions_order',
            field=models.CharField(default='order', max_length=25),
        ),
    ]
