# Generated by Django 2.0.2 on 2019-01-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_auto_20190112_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='questions_order',
            new_name='question_order',
        ),
    ]
