# Generated by Django 2.0.2 on 2019-01-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='question',
        ),
    ]
