# Generated by Django 2.0.2 on 2019-01-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_remove_fileupload_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_files', to='quizzes.Question'),
            preserve_default=False,
        ),
    ]
