# Generated by Django 2.0.2 on 2019-01-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_fileupload_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='File',
        ),
    ]
