# Generated by Django 2.0.2 on 2019-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_auto_20190116_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
