# Generated by Django 2.0.2 on 2019-01-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0027_auto_20190118_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='answer_text',
            new_name='student_answer_text',
        ),
    ]
