# Generated by Django 2.0.2 on 2019-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_auto_20190118_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='result',
            name='student_answer_text',
        ),
    ]
