# Generated by Django 2.0.2 on 2019-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_auto_20190121_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='student_answer',
            new_name='answer_text',
        ),
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.BooleanField(),
        ),
    ]
