# Generated by Django 2.0.2 on 2019-01-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_auto_20190121_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark_divided',
            field=models.FloatField(null=True),
        ),
    ]
