# Generated by Django 2.0.2 on 2019-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_question_mark_divided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark_divided',
            field=models.FloatField(default=models.FloatField(null=True), null=True),
        ),
    ]
