# Generated by Django 2.0.2 on 2019-02-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0036_auto_20190127_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='do_not_know',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
