# Generated by Django 2.0.2 on 2019-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0037_auto_20190201_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
