# Generated by Django 2.0.2 on 2019-02-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0039_auto_20190212_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.ClassGroup'),
        ),
    ]
