# Generated by Django 2.1.7 on 2019-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_classgroup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='color',
            field=models.CharField(default='blue', max_length=10),
            preserve_default=False,
        ),
    ]
