# Generated by Django 2.1.7 on 2019-03-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0043_quiz_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='question',
        ),
        migrations.AlterField(
            model_name='result',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quizzes.Question'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
